// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  alternate_grid: defineAsyncComponent(
    () => import("./AlternateGrid/index.vue"),
  ),
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue"),
  ),
  customer_logos: defineAsyncComponent(
    () => import("./CustomerLogos/index.vue"),
  ),
  faq: defineAsyncComponent(() => import("./Faq/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  simple_hero: defineAsyncComponent(() => import("./SimpleHero/index.vue")),
});
